version: '3.8'
services:
  db:
    image: 'postgres:17.5'
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=employee_db
    volumes:
      - db-data:/var/lib/postgresql/data/
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db-data: